spring:
  application:
    name: service-3
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
server:
  port: ${SERVER_PORT:8030}
feign:
  hystrix:
    enabled: false