spring:
  application:
    name: eureka
eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 5000
    peerNodeConnectionIdleTimeoutSeconds: 5
    renewalThresholdUpdateIntervalMs: 10000
    peerEurekaStatusRefreshTimeIntervalMs: 10000
    peerEurekaNodesUpdateIntervalMs: 10000
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
security:
  basic:
    path: /**
  user:
    name: ${EUREKA_USERNAME:istanbul}
    password: ${EUREKA_PASSWORD:coders}

server:
  port: ${SERVER_PORT:8761}